Apply linting suggestions to oscal-rest yaml files
EasyDynamics/oscal-rest pull request #26
Opened 2021-07-06 18:19 UTC by tuckerzp

This adds the ability to lint `.yaml` files as well as updates the `README` to describe those changes.

2021-07-07 00:12 UTC, rgauss reviewed
One of the major concerns in encouraging/enforcing linting is that we need to conform to whatever Swagger Editor's YAML formatting defaults are.  From some quick tests, it looks like this still follows that app's format, so I think we're good.

@kylelaker has good comments as well.

Note that this does not need to block the actual open sourcing of this repository.

2021-07-08 15:33 UTC, kylelaker requested changes
This is good but a few quick requests:
 - I don't think that `.github/worfklows/pr.yml` needs all these comments; lots of them explain how GHA works. I think these come from their template? Let's yank those
 - `main` needs to be added to the list of branches to trigger on push.
 - need a comment explaining why that YAML Lint rule is disabled on line 6 (bc GH requires `on`)
 - can we specify `ubuntu-20.04` instead of `ubuntu-latest`? GHA does a very slow and wonky migration when a new LTS comes out. let's just stick with one version
 - please remove `workflow_dispatch` as a trigger (we don't want to trigger this manually)
 -

2021-07-08 15:39 UTC, kylelaker approved these changes
Thanks for cleaning all that up!

2021-07-08 15:56 UTC, zclarkEDC approved these changes

2021-07-08 16:22 UTC, merged