Include root object wrapper in requests/responses
EasyDynamics/oscal-rest pull request #37
Opened 2022-01-18 21:46 UTC by mikeisen1

Include the root object wrapper, like `component-definition`, so the requests and responses match their OSCAL JSON schema.

Closes #33

2022-01-18 21:58 UTC, rgauss requested changes
For consistency, can we wrap the other schemas as well?

Even though OSCAL doesn't define them as root document objects we want the REST API to treat them just as any other first-class object.

2022-01-20 17:39 UTC, mikeisen1 commented
For each of the other schemas, they normally appear as object in an array and do not have an object wrapper name. So for those I will take the name of the array they appear in and use the singular form of it.

2022-01-20 20:43 UTC, rgauss approved these changes

2022-01-21 21:47 UTC, hreineck approved these changes

2022-01-21 21:47 UTC, merged